name: fagopay
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+11

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  dotted_decoration: ^2.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_native_contact_picker: ^0.0.3
  flutter_progress_hud: ^2.0.2
  flutter_svg: 
  freezed_annotation: ^2.2.0
  get: ^4.6.5
  go_router: ^0.0.1
  http: ^0.13.5
  intl: ^0.18.0
  numeric_keyboard: ^1.1.0
  pin_code_fields: ^7.4.0
  shared_preferences: ^2.0.18
  sizer: ^2.0.15
  url_launcher: ^6.1.10
  # webview_flutter: ^4.0.7
  smooth_page_indicator: ^1.0.0
  flutter_secure_storage: ^8.0.0
  percent_indicator: ^4.2.3
  flutter_identity_kyc: ^0.1.5
  permission_handler: ^10.2.0
  fluttertoast: ^8.2.1
  pin_code_text_field: ^1.8.0
  number_display: ^3.0.0

dev_dependencies:
  build_runner: ^2.3.3

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    # - images/

  fonts:
    - family: Work Sans
      fonts:
        - asset: assets/fonts/WorkSans-Bold.ttf
        - asset: assets/fonts/WorkSans-ExtraBold.ttf
        - asset: assets/fonts/WorkSans-Light.ttf
        - asset: assets/fonts/WorkSans-Regular.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito-ExtraBold.ttf
        - asset: assets/fonts/Nunito-Light.ttf
        - asset: assets/fonts/Nunito-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  